### ISSUE TITLE
Create Job is failing - any idea on this error

### ISSUE THREAD

**Issue by knadendla** [RisingOak/jenkins-client#121]
<project>
      <actions/>
      <description></description>
      <keepDependencies>false</keepDependencies>
      <properties/>
      <scm class="hudson.scm.NullSCM"/>
      <canRoam>true</canRoam>
      <disabled>false</disabled>
      <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
      <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
      <triggers/>
      <concurrentBuild>false</concurrentBuild>
      <builders/>
      <publishers/>
      <buildWrappers/>
    </project>

Kishore{testjob=com.offbytwo.jenkins.model.Job@6a2105a4}
Kishoretrue
org.apache.http.client.HttpResponseException: Not Found
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:139)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:249)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:243)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:199)

**Comment by heemin32** [comment]
Try to call `createJob(jobName, jobXml, false)`
I do not know what `crumbFlag` is for but in my case setting `crumbFlag` as `false` works without error.

**Comment by khmarbaise** [comment]
Can you give a little bit more details like which version of Jenkins you have used? Which version of the jenkins-client API you have used ? And is this the full stack trace?
