### ISSUE TITLE
Doocumentation?

### ISSUE THREAD

**Issue by deanthomsen** [RisingOak/jenkins-client#134]
Is there any documentation or code examples on how to use this pretty nice looking API?  I've walked through some of the code and the test source to try and figure it out, but still not sure how to use it.  For example, how to I initiate a build?  Tried the JobWithDetails.build() method but get an http not found exception and don't understand what's missing. That's just an example... I also followed the instructions for doing an anonymous clone of the repository so I could more easily walk through the code (as described [here](http://risingoak.github.io/jenkins-client/source-repository.html)) and that failed with permission denied.  Bottom line... how do I learn how to use your API?  Thanks

**Comment by deanthomsen** [comment]
1) Never mind the clone issue, I figured that out.  
2) The job.build() "not found" error comes from this: Crumb crumb = getQuietly("/crumbIssuer", Crumb.class);  Apparently "crumbIssuer" is not a supported resource on my Jenkins server. So I always need to set th crumpFlag to false.
3) I also learned that you can't use job.build(false) for a paramterized job, which is the real reason that I could not build the job.  You need to use job.build(new HashMap<String, String>(), false);  The tricky thing is figuring out if a build is parameterized or not.  So I eventually ended up with this little snippet of code, which is not perfect but works OK.

        if (job.getLastBuild().details().getParameters().isEmpty()) {
            job.build(false);
        } else {
            QueueReference qr = job.build(new HashMap<String, String>(), false);
            System.out.println("Job started on queue: " + qr.getQueueItemUrlPart());
        }

Would still love to see some documentation or sample code.

**Comment by khmarbaise** [comment]
Hi,
first thanks for your comments and of course it would be really nice having a documentation apart from the source code (which is the only truth...)...

The simplest solution to start with a documentation is to make it part of the [generated site](http://risingoak.github.io/jenkins-client/). This can be done in Markdown etc. or in Maven APT etc. but i would prefer markdown or asciidoc which is also possible..I have created an issue #135 for that and i will make a basic setup for it....May be you can help to write documentation?

So about 2 i would ask which Jenkins version are you using? 
About 3 looks like a improvement request to make it more convenient to use the API here.. May be you can create an appropriate Pull request for it (create an issue before it)...Would be great..

Kind regards
Karl Heinz

**Comment by cod3min3** [comment]
@deanthomsen Can you explain your solution to 2 further please? I have this code snipped and I'm getting a similar error to you
    JenkinsHttpClient client = new JenkinsHttpClient(new URI("http://localhost:8070"), Constants.JENKINS_USER, Constants.JENKINS_PASSWORD);
    JenkinsServer jenkins = new JenkinsServer(client);
    Map<String, Job> jobs = jenkins.getJobs();
    JobWithDetails job = jobs.get("My Job").details();

**Comment by khmarbaise** [comment]
What kind of error do you get exactly? Which version of the java client api are you using) 0.3.7 ?

**Comment by cod3min3** [comment]
@khmarbaise 

`Exception in thread "main" org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:134)
	at com.offbytwo.jenkins.model.Job.details(Job.java:45)
	at com.axa.viz.console.core.Tester.main(Tester.java:24)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 11 more
`
What id odd is that it's saying that the connection was refused at port 8080 even though I specified the URI as `http://localhost:8070`

Thanks for the help

**Comment by khmarbaise** [comment]
Have you installed Jenkins plain as war and started via java -jar jenkins.war ? Or do you have something in between like an Apache with redirection? Or do you have running a firewall locally cause the error message lets me assume something like this?

**Comment by cod3min3** [comment]
I found out what was causing the problem. I had changed the what port jenkins was running on to 8070. I done that change though jenkins.xml. But that wasn't enough, I also had to change the "Jenkins URL" in Configure Systems. Before I changed it, it was localhost:8080, and that was what was getting displayed in the exception.
