### ISSUE TITLE
JsonMappingException

### ISSUE THREAD

**Issue by MickeArv** [RisingOak/jenkins-client#141]
I have downloaded the latest Jenkins and I get the following stacktrace:
`com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.offbytwo.jenkins.model.BuildChangeSet out of START_ARRAY token
 at [Source: [B@475c9c31; line: 1, column: 388] (through reference chain: com.offbytwo.jenkins.model.BuildWithDetails["changeSet"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:685)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1215)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2167)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.objectFromResponse(JenkinsHttpClient.java:438)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:147)
	at com.offbytwo.jenkins.model.Build.details(Build.java:43)`

**Comment by yongwoohan** [comment]
me too

**Comment by khmarbaise** [comment]
#138 So already three so i close this issue.
