### ISSUE TITLE
deleteJob throws exception but works anyway...

### ISSUE THREAD

**Issue by cshupp1** [RisingOak/jenkins-client#154]
Consider the following JRuby code:

```
java_import 'com.offbytwo.jenkins.JenkinsServer' do |p, c|
  'JenkinsServer'
end
  jenkins = JenkinsServer.new(java.net.URI.new("some_url"), "user", "password")
  xml = IO.read('./config.xml')
jenkins.createJob("cris", xml, false)
```

The job does show up in Jenkins as expected.

If I delete the job it deletes it as expected:
```
jenkins.deleteJob("cris")
```

But it throws an exception:
```
irb(main):022:0>   jenkins.deleteJob("cris")
org.apache.http.client.HttpResponseException: Not Found
        at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:146)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.getQuietly(JenkinsHttpClient.java:186)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:226)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:397)
        at com.offbytwo.jenkins.JenkinsServer.deleteJob(JenkinsServer.java:482)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:452)
```

So, for clarity, the job is deleted from Jenkins, but it appears to have failed.  I am using 0.3.3.
Jenkins ver. 1.656

**Comment by khmarbaise** [comment]
Can you check if it happens with the current state of Jenkins Client ?

**Comment by cshupp1** [comment]
What should I use?

I am using this right now:
```
    <dependency>
    <groupId>com.offbytwo.jenkins</groupId>
    <artifactId>jenkins-client</artifactId>
    <version>0.3.3</version>
    </dependency>
```

**Comment by khmarbaise** [comment]
Please use new release version 0.3.4

**Comment by cshupp1** [comment]
0.3.4 is not out there.

http://mvnrepository.com/artifact/com.offbytwo.jenkins/jenkins-client

Now what?  Is it in a private repo?

**Comment by khmarbaise** [comment]
You should look here: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.offbytwo.jenkins%22%20a%3A%22jenkins-client%22 cause this is maven Central. I don't know in which intervals mvnrepository.com will be synched....

**Comment by cshupp1** [comment]
Thanks!

**Comment by darmbrust** [comment]
Hi, 
I work with Cris - for whatever reason, our nexus repo which mirrors from central was unable to find 0.3.4, then a quick google search lead to the link above, which also didn't show it.... I'll take another look at our nexus config and try to figure out why it couldn't find it on central.

**Comment by khmarbaise** [comment]
You mean the mvnrepository.com didn't showed it? Does you nexus update the central index on a regular basis? Maybe only once a week ? That's often the problem...Just let your nexus pick update the index more often..may be once per day...

**Comment by darmbrust** [comment]
Must have been an interval miss or something - I see that our local nexus repo has picked it up now.
