### ISSUE TITLE
NoSuchMethodError when calling JenkinsServer(url, username, password)

### ISSUE THREAD

**Issue by emmaLP** [RisingOak/jenkins-client#48]
Upon investigation, it seems that the jackson-mapper-asl is not compatible with spring 3.2. You would need to use fastxml jackson pom  dependencies. Please see the url below for the changes http://wiki.fasterxml.com/JacksonUpgradeFrom19To20

Stacktrace:
java.lang.NoSuchMethodError: org.codehaus.jackson.map.DeserializationConfig.without([Lorg/codehaus/jackson/map/DeserializationConfig$Feature;)Lorg/codehaus/jackson/map/DeserializationConfig;
at com.offbytwo.jenkins.client.JenkinsHttpClient.getDefaultMapper(JenkinsHttpClient.java:232)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.<init>(JenkinsHttpClient.java:53)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.<init>(JenkinsHttpClient.java:65)
	at com.offbytwo.jenkins.JenkinsServer.<init>(JenkinsServer.java:46)

Is it possible to get this fixed ASAP?

**Comment by emmaLP** [comment]
I have managed a work around, but I would still recommend upgrading.

**Comment by gmaslowski** [comment]
done: https://github.com/RisingOak/jenkins-client/pull/50

Waiting for merge.
