### ISSUE TITLE
"org.apache.http.client.HttpResponseException: Not Found" when creating a new job in 0.3.0 version

### ISSUE THREAD

**Issue by estebanwasinger** [RisingOak/jenkins-client#51]
In my Java App i do the following: 
```java
 jenkins.createJob("my-new-job", config.toString());
```
(where "config.toString() is the XML config.)

**My App works perfectly with 0.2.0 version.**

An exception is thrown with following stack trace:
```
org.apache.http.client.HttpResponseException: Not Found
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:108)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:206)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:200)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:167)
	at jenkins.automation.SettingsHelperTest.testRubickConfig(SettingsHelperTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by Fritte** [comment]
I had the same issue when I tried to upgrade jenkins-client from 0.2.0 to 0.2.2.

**Comment by gmaslowski** [comment]
Need some more details about it. 

The https://github.com/gmaslowski/jenkins-client/blob/master/src/test/java/com/offbytwo/jenkins/integration/JenkinsServerIntegrationTest.java#L126 doesn't fail.

**Comment by estebanwasinger** [comment]
Hi @gmaslowski 
I been debugged the code in the post_xml method, what i could see is the following:

**[post_xml method version:0.3.0]**
```java
public String post_xml(String path, String xml_data, boolean crumbFlag) throws IOException {
        HttpPost request = new HttpPost(api(path));
        if (crumbFlag == true) {
            Crumb crumb = get("/crumbIssuer", Crumb.class);
            if (crumb != null) {
                request.addHeader(new BasicHeader(crumb.getCrumbRequestField(), crumb.getCrumb()));
            }
        }
....
....
```

**[post_xml method version:0.2.0]**
```java
public String post_xml(String path, String xml_data) throws IOException, HttpResponseException {
        HttpPost request = new HttpPost(api(path));
        if (xml_data != null) {
            request.setEntity(new StringEntity(xml_data, ContentType.APPLICATION_XML));
        }
        HttpResponse response = client.execute(request, localContext);
        int status = response.getStatusLine().getStatusCode();
        if (status < 200 || status >= 300) {
````

The version 0.3.0 tries to make a a call **"GET http://localhost:8080/crumbIssuer/api/json HTTP/1.1"** this URL in my Jenkins Server doesn't exist, i don't know what is the crumbIssuer, but it seems that doesn't existe in my local server and in my CloudBees Jenkins Instance.
Nor is there a way to disable it, the crumbFlag is hardcoded always to true.
In case of **updateJob** you can 
updating specifying the crumbFlag value:
```java
public void updateJob(String jobName, String jobXml, boolean crumbFlag)
```
or
using the default value:
```java
public void updateJob(String jobName, String jobXml)
```
in createJob the only available method is:
```java
public void createJob(String jobName, String jobXml)
```

I made a Pull Request fixing this problem, i tested and it's working perfect
https://github.com/RisingOak/jenkins-client/pull/52

Thanks
Esteban

**Comment by khmarbaise** [comment]
Based on reference to #56 i will close this issue as solved if you have any further issue please create a new issue.
