### ISSUE TITLE
Illegal Charset when passing parameters

### ISSUE THREAD

**Issue by rgururaj** [RisingOak/jenkins-client#9]
JenkinsHttpClient client = new JenkinsHttpClient(new URI("xxx"), "admin", "token");
		HashMap<String, String> params = new HashMap();
		params.put("test", "test");
		
		ObjectMapper mapper = new ObjectMapper();
        DeserializationConfig deserializationConfig = mapper.getDeserializationConfig();
        mapper.setDeserializationConfig(deserializationConfig.without(DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES));
        
        System.out.println(mapper.writeValueAsString(params));
		client.post("build", params, null); 

The above code throws below exception.

{"test":"test"}
Exception in thread "main" java.nio.charset.IllegalCharsetNameException: application/json
	at java.nio.charset.Charset.checkName(Charset.java:284)
	at java.nio.charset.Charset.lookup2(Charset.java:458)
	at java.nio.charset.Charset.lookup(Charset.java:437)
	at java.nio.charset.Charset.forName(Charset.java:502)
	at org.apache.http.entity.ContentType.create(ContentType.java:180)
	at org.apache.http.entity.StringEntity.<init>(StringEntity.java:127)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:136)

**Comment by khmarbaise** [comment]
If i correctly look into the code this has already been fixed...If not don't hesitate to reopen the issue...
